name: External Trigger Main

on:
  #schedule:
  #  - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  external-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: External Trigger
        run: |
          echo "external trigger running off of test branch"
