name: Testing

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: '0'
        
      - name: Testing
        run: |
          #echo "PAUSE_TRIGGER_NAME=TESTING" >> $GITHUB_ENV
          export PAUSE_TRIGGER_NAME="TESTING"
          pause_trigger=${{ secrets[env.PAUSE_TRIGGER_NAME] }}
          if [ "$pause_trigger" == "true" ]; then
            echo "successful"
          else
            echo "not successful"
          fi
