name: Package Trigger Test

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  package-trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Package Trigger Test
        run: |
          echo "testing"
